'use client';
import { useState } from 'react';
import { XMarkIcon, TruckIcon, MapPinIcon, CheckBadgeIcon, ExclamationTriangleIcon, PlusIcon, InboxStackIcon } from '@heroicons/react/24/outline';
import { toast } from 'react-hot-toast';

export default function OrderDetailsModal({ order, onClose, mutate }: { order: any, onClose: () => void, mutate: () => void }) {
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [fulfillments, setFulfillments] = useState<any[]>(order?.fulfillments || []);

    const handleCreateFulfillment = async () => {
        if (!confirm("Allocate all pending unfulfilled items into a new Shipment tracking box?")) return;
        setIsSubmitting(true);
        try {
            const itemIds = order.items
                .filter((item: any) => !fulfillments.some((f: any) => f.items?.some((fi: any) => fi.orderItemId === item.id)))
                .map((item: any) => item.id);

            if (itemIds.length === 0) {
                toast.error("No unfulfilled items available globally.");
                return;
            }

            const res = await fetch(`/api/oms/orders/${order.id}/fulfillments`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ itemIdsToFulfill: itemIds })
            });

            const data = await res.json();
            if (!res.ok) throw new Error(data.error || "Failed to split shipment.");

            toast.success("📦 Auto-Split Fulfillment Initiated!");
            mutate(); // Refresh the parent SWR table globally
            onClose(); // Automatically close the DOM Drawer
        } catch (error: any) {
            toast.error(error.message);
            console.error(error);
        } finally {
            setIsSubmitting(false);
        }
    };

    const handleAILogisticsRouting = async () => {
        if (!confirm("Allow Gemini AI to autonomously calculate the most profitable Multi-Warehouse route and execute Split Fulfillments?")) return;
        setIsSubmitting(true);
        try {
            toast.loading("🧠 AI calculating optimal shipping paths...", { duration: 3000 });
            const res = await fetch(`/api/oms/orders/${order.id}/dom`, { method: "POST" });
            const data = await res.json();
            if (!res.ok) throw new Error(data.error || "AI DOM Engine Error.");

            toast.success(`✨ Routes generated by AI (${data.fulfillmentsGenerated} boxes)!`);
            console.log("AI Logistics Output:", data.decisions);
            mutate();
            onClose();
        } catch (error: any) {
            toast.error(error.message);
            console.error(error);
        } finally {
            setIsSubmitting(false);
        }
    };

    if (!order) return null;

    const unfulfilledItems = order.items?.filter((item: any) => {
        // Check if item is already in a fulfillment
        const isInFulfillment = fulfillments.some(f => f.items?.some((fi: any) => fi.orderItemId === item.id));
        return !isInFulfillment;
    }) || [];

    return (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex justify-end">
            <div className="bg-white w-full max-w-2xl h-full shadow-2xl flex flex-col animate-slide-in-right overflow-y-auto">
                {/* Header */}
                <div className="bg-gradient-to-r from-gray-900 to-indigo-900 p-6 flex justify-between items-center text-white sticky top-0 z-10">
                    <div>
                        <div className="flex items-center gap-3">
                            <h2 className="text-2xl font-black tracking-tight">Order #{order.id.slice(-6).toUpperCase()}</h2>
                            <span className="px-2 py-1 bg-white/20 rounded text-xs font-bold">{order.channel}</span>
                        </div>
                        <p className="text-indigo-200 text-sm mt-1">{new Date(order.createdAt).toLocaleString()} • {order.customer?.name || 'Guest Checkout'}</p>
                    </div>
                    <button onClick={onClose} className="p-2 hover:bg-white/20 rounded-full transition">
                        <XMarkIcon className="w-6 h-6" />
                    </button>
                </div>

                {/* Body */}
                <div className="p-6 space-y-8 flex-1">

                    {/* Customer Info */}
                    <div className="bg-gray-50 border border-gray-100 rounded-2xl p-5 flex items-start gap-4">
                        <div className="p-3 bg-indigo-100 text-indigo-600 rounded-xl">
                            <MapPinIcon className="w-6 h-6" />
                        </div>
                        <div>
                            <h3 className="font-bold text-gray-900 text-lg">Delivery Profile</h3>
                            <p className="text-gray-600 mt-1">{order.customer?.address || 'No physical address recorded.'}</p>
                            <p className="text-gray-500 text-sm mt-1">{order.customer?.province} {order.customer?.zipCode}</p>
                        </div>
                    </div>

                    {/* Fulfillments (DOM) */}
                    <div>
                        <div className="flex items-center justify-between mx-1 mb-4">
                            <h3 className="text-xl font-bold flex items-center gap-2">
                                <TruckIcon className="w-6 h-6 text-indigo-500" />
                                Shipments / Fulfillments
                            </h3>
                            <button onClick={handleCreateFulfillment} className="flex items-center gap-2 text-sm font-bold text-indigo-600 bg-indigo-50 px-4 py-2 rounded-lg hover:bg-indigo-100 transition">
                                <PlusIcon className="w-4 h-4" /> Split Shipment
                            </button>
                        </div>

                        {fulfillments.length === 0 ? (
                            <div className="p-6 border-2 border-dashed border-gray-200 rounded-2xl text-center flex flex-col items-center">
                                <InboxStackIcon className="w-10 h-10 text-gray-300 mb-2" />
                                <span className="text-gray-500 font-medium">No fulfillments generated yet.</span>
                                <span className="text-sm text-gray-400">All items are currently unfulfilled.</span>
                            </div>
                        ) : (
                            <div className="space-y-4">
                                {fulfillments.map((f, i) => (
                                    <div key={f.id || i} className="border border-gray-200 rounded-2xl p-5 shadow-sm">
                                        <div className="flex justify-between items-center mb-3">
                                            <span className="font-bold text-indigo-900 bg-indigo-50 px-3 py-1 rounded-full text-xs">📦 Package #{i + 1}</span>
                                            <span className="text-xs font-bold text-gray-500">{f.status}</span>
                                        </div>
                                        <div className="text-sm text-gray-600 mb-3">Courier: {f.courier || 'Pending'} • Tracking: {f.trackingNumber || 'Pending'}</div>
                                        {/* Items in this fulfillment */}
                                        <div className="bg-gray-50 rounded-xl p-3 space-y-2">
                                            {f.items?.map((fi: any) => (
                                                <div key={fi.id} className="flex justify-between items-center text-sm">
                                                    <span className="font-medium">{fi.orderItem?.productName || 'Unknown Item'}</span>
                                                    <span className="font-bold text-indigo-600">x{fi.quantity}</span>
                                                </div>
                                            ))}
                                        </div>
                                    </div>
                                ))}
                            </div>
                        )}
                    </div>

                    {/* Unfulfilled Items */}
                    {unfulfilledItems.length > 0 && (
                        <div className="pt-4 border-t border-gray-100">
                            <h4 className="font-bold text-rose-600 mb-3 flex items-center gap-2">
                                <ExclamationTriangleIcon className="w-5 h-5" /> Pending Unfulfilled Items
                            </h4>
                            <div className="bg-rose-50 border border-rose-100 rounded-2xl overflow-hidden">
                                {unfulfilledItems.map((item: any) => (
                                    <div key={item.id} className="p-4 border-b border-rose-100 last:border-0 flex justify-between items-center bg-white hover:bg-rose-50/50 transition">
                                        <div>
                                            <h5 className="font-bold text-gray-900">{item.productName}</h5>
                                            <p className="text-xs text-gray-500 mt-1">Price: ฿{item.price}</p>
                                        </div>
                                        <div className="font-black text-rose-600 bg-rose-100 px-3 py-1 rounded-lg">x{item.quantity}</div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}
                </div>

                {/* Footer */}
                <div className="p-6 border-t border-gray-100 bg-gray-50 flex items-center justify-between">
                    <div>
                        <span className="text-gray-500 text-sm font-medium">Net Value</span>
                        <div className="text-2xl font-black text-emerald-600">฿{order.total?.toLocaleString() || '0'}</div>
                    </div>
                    {unfulfilledItems.length > 0 && (
                        <div className="flex gap-3">
                            <button disabled={isSubmitting} onClick={handleAILogisticsRouting} className="bg-gradient-to-r from-purple-500 to-indigo-600 hover:opacity-90 text-white px-8 py-3 rounded-xl font-bold transition shadow-lg shadow-purple-500/30 flex items-center gap-2">
                                🧠 {isSubmitting ? 'Calculating Routes...' : 'Ask AI to Auto-Route'}
                            </button>
                            <button disabled={isSubmitting} onClick={handleCreateFulfillment} className="bg-white border-2 border-indigo-100 text-indigo-600 hover:bg-indigo-50 px-8 py-3 rounded-xl font-bold transition">
                                {isSubmitting ? 'Generating...' : 'Fulfill Manually'}
                            </button>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
